package Internacionalizacao;

public class Internacionalizacao 
{
	
	public String lang = "pt";
	public String Sim = "Sim", Nao = "não",
			CadastrarAeronave = "Cadastrar Aeronave",
			NomeAeronave = "Nome da Aeronave", 
			ModeloAeronave = "Modelo da Aeronave", 
			QuantidadeColunas = "Quantidade de Colunas de Assento", 
			QuantidadeFileiras = "Quantidade de Fileiras de Assento",
			Cadastrar = "Cadastrar",
			CadastrarPassageiro = "Cadastrar Passageiro",
			CodigoPassageiro = "Codigo do Passageiro", 
			Limpar = "Limpar",
			Tipo = "Tipo de Passageiro",
			RG = "RG",
			CPF = "CPF", 
			Tratamento = "Tratamento", 
			DataNascimento = "Data de Nascimento",
			Celular ="Número do Celular",
			Email = "Email",
			ExcluirPassageiro = "Excluir Passageiro",
			Masculino = "Masculino",
			Feminino = "Feminino",
			Genero = "Genero",
			AlterarPassageiro = "Alterar Passageiro",
			ConsultarPassageiro = "Consultar Passageiro",
			ListaDeAeronave = "Lista de Aeronaves",
			ListaDePassageiro = "Lista de Passageiros",
			Ambos="Ambos",
			Dia = "Dia",
			Mes = "Mês",
			Ano = "Ano",
			Sobre = "Sobre",
			MenuPrincipal = "Menu Principal",
		  IncluirEscalas = "Incluir Escalas",
		  ExcluirEscalas = "Excluir Escalas",
		  Salvar = "Salvar",
		  AlterarVoo = "Alterar Voo",
		  CodigoVoo = "Código do Voo",
		  Origem = "Origem",
		  Escalas = "Escalas",
		  Destino = "Destino",
		  Data = "Data",
		  Hora = "Hora",
		  Situacao = "Situação",
		  EmEspera = "Em espera",
		  Preco = "Preço",
		  Nome = "Nome",
		  QuantidadeAssentos = "Quantidade assentos",
		  AdicionarEscalas = "Adicionar Escalas",
		  EscalasVoo = "Escalas Voo",
		  CadastrarVoo = "Cadastrar Voo",
		  CancelarPassagem = "Cancelar Passagem",
		  CodigoBilhete = "Código do bilhete",
		  TempoRestante = "Tempo restante",
		  ValorDevolvido = "Valor a ser devolvido",
		  ContaBancaria = "Conta Bancária",
		  Banco = "Banco",
		  Agencia = "Agência",
		  NumeroDaConta = "Número da conta",
		  NomeTitular = "Nome do titular",
		  CPFTitular = "CPF titular",
		  RealizarNovaPesquisa = "Realizar nova pesquisa",
		  CodigoAeronave = "Código Aeronave",
		  ConsultarAeronave = "Consultar Aeronave",
		  Detalhes = "Detalhes",
		  Buscar = "Buscar",
		  RealizarNovaConsulta = "Realizar nova consulta",
		  ListarEscalasIda = "Listar escalas ida",
		  Comprar = "Comprar",
		  ListarEscalasVolta = "Listar escalas volta",
		  ConsultarVoo = "Consultar Voo",
		  DataPartida = "Data da partida",
		  HoraPartida = "Hora partida",
		  AeroportoDestino = "Aeroporto de destino",
		  CidadeDestino = "Cidade de destino",
		  CustoIda = "Custo ida",
		  CustoVolta = "Custo volta",
		  CustoTotal = "Custo total",
		  ListarEscalas = "Listar escalas",
		  Voltar = "Voltar",
		  ConsultarVooIdaEVolta = "Consultar Voo Ida e Volta",
		  Ida = "Ida",
		  Volta = "Volta",
		  DataIda = "Data de ida",
		  DataVolta = "Data da volta",
		  Passageiros1 = "Passageiros (até 1 ano e 11 meses)",
		  Passageiros2 = "Passageiros (até 2 anos e 11 meses)",
		  Passageiros3 = "Passageiros (acima de 3 anos)",
		  IdaVolta = "Ida e Volta",
		  SomenteIda = "Somente Ida",
		  Pesquisar = "Pesquisar",
		  AlterarStatusVoo = "Alterar Status de Voo",
		  ControlarStatusVoo = "Controlar Status de Voo",
		  AlterarStatus = "Alterar Status",
		  Codigo = "Código",
		  AlterarAeronave = "Alterar Aeronave",
		  Modelo = "Modelo",
		  Consultar = "Consultar",
		  Excluir = "Excluir",
		  Alterar = "Alterar",
		  ExcluirAeronave = "Excluir Aeronave",
		  TipoAeronave = "Tipo da Aeronave",
		  ExcluirVoo = "Excluir Voo",
		  ListaDeEscalas = "Lista de Escalas",
		  RealizarCompra = "Realizar Compra",
		  TransferirPassagem = "Transferir Passagem",
		  SistemaAeroporto = "Sistema Aeroporto",
		  Arquivo = "Arquivo",
		  Sair = "Sair",
		  Passagem = "Passagem",
		  ComprarPassagem = "Comprar Passagem",
		  CheckIn = "Check-In",
		  RealizarCheckIn = "Realizar Check-In",
		  Aeronave = "Aeronave",
		  Voo = "Voo",
		  Ajuda = "Ajuda",
		  Suporte = "Suporte",
		  PassagemAerea = "Passagem Aerea",
		  Voos = "Voos",
		  Finalizar = "Finalizar",
		  Sobrenome = "Sobrenome",
		  DataDeNascimento = "Data de nascimento",
		  ListarAssentosDisponiveis = "Listar Assentos Disponíveis",
		  PerfilPassageiro = "Perfil Passageiro",
		  FormaDeTratamento = "Forma de tratamento",
		  Adicionar = "Adicionar",
		  TipoPagamento = "Tipo de Pagamento",
		  Cartao = "Cartão",
		  NomeTitularCartao = "Nome titular do cartão",
		  Debito = "Débito",
		  Credito = "Crédito",
		  BandeiraCartao = "Bandeira Cartão",
		  NumeroCartao = "Número Cartão",
		  DataValidadeCartao = "Data validade cartão",
		  NumeroSegurancaCartao = "Número de segurança do cartão",
		  NumeroParcelas = "Número de parcelas",
		  ValorParcela = "Valor da parcela",
		  Dinheiro = "Dinheiro",
		  ValorPago = "Valor pago",
		  ValorTotal = "Valor total",
		  ValorTroco = "Valor troco",
		  Cheque = "Cheque",
		  Conta = "Conta",
		  FinalizarCompra = "Finalizar Compra",
		  ListarAssentos = "Listar assentos",
		  TransferirAssentos = "Transferir assentos",
		  CodigoPassagem = "Código da passagem",
		BuscarVoo = "Buscar Voo",
		ConsultarVooPassagem = "Consultar Voo - Pasagem",
		Titulo = "Sistema Passagem Aerea",
		TipoPesquisa = "Tipo de Pesquisa",
		DadosVoo = "Dados do Voo",
		SomenteCodigo = "Somente pelo Código",
		Confirmado = "Confirmado",
		Encerrado = "Encerrado",
		Passageiro = "Passageiro",
		Senhora = "Senhora",
		Senhorita = "Senhorita",
		Senhor = "Senhor",
		QuantidadePassageiros = "Quantidade Passageiros",
		AssentosDisponiveis = "Assentos Disponíveis",
		numeroCheque = "Número cheque";
	
	public   void toPortuguese()
	{
		 Sim = "Sim";
		 Nao = "não";
		Titulo = "Sistema Passagem Aerea";
		IncluirEscalas = "Incluir Escalas";
		ExcluirEscalas = "Excluir Escalas";
		Salvar = "Salvar";
		AlterarVoo = "Alterar Voo";
		CodigoVoo = "Código do Voo";
		Origem = "Origem";
		Escalas = "Escalas";
		Destino = "Destino";
		Data = "Data";
		Hora = "Hora";
		NomeAeronave = "Nome da Aeronave";
		Situacao = "Situação";
		EmEspera = "Em espera";
		Preco = "Preço";
		Nome = "Nome";
		QuantidadeAssentos = "Quantidade assentos";
		CadastrarAeronave = "Cadastrar Aeronave";
		QuantidadeFileiras = "Quantidade fileiras";
		AdicionarEscalas = "Adicionar Escalas";
		EscalasVoo = "Escalas Voo";
		CadastrarVoo = "Cadastrar Voo";
		CancelarPassagem = "Cancelar Passagem";
		CodigoBilhete = "Código do bilhete";
		TempoRestante = "Tempo restante";
		ValorDevolvido = "Valor a ser devolvido";
		ContaBancaria = "Conta Bancária";
		Banco = "Banco";
		Agencia = "Agência";
		NumeroDaConta = "Número da conta";
		NomeTitular = "Nome do titular";
		CPFTitular = "CPF titular";
		RealizarNovaPesquisa = "Realizar nova pesquisa";
		CodigoAeronave = "Código Aeronave";
		ConsultarAeronave = "Consultar Aeronave";
		Detalhes = "Detalhes";
		Buscar = "Buscar";
		RealizarNovaConsulta = "Realizar nova consulta";
		ListarEscalasIda = "Listar escalas ida";
		Comprar = "Comprar";
		ListarEscalasVolta = "Listar escalas volta";
		ConsultarVoo = "Consultar Voo";
		DataPartida = "Data da partida";
		HoraPartida = "Hora partida";
		AeroportoDestino = "Aeroporto de destino";
		CidadeDestino = "Cidade de destino";
		CustoIda = "Custo ida";
		CustoVolta = "Custo volta";
		CustoTotal = "Custo total";
		ListarEscalas = "Listar escalas";
		Voltar = "Voltar";
		ConsultarVooIdaEVolta = "Consultar Voo Ida e Volta";
		Ida = "Ida";
		Volta = "Volta";
		DataIda = "Data de ida";
		DataVolta = "Data da volta";
		Passageiros1 = "Passageiros (até 1 ano e 11 meses)";
		Passageiros2 = "Passageiros (até 2 anos e 11 meses)";
		Passageiros3 = "Passageiros (acima de 3 anos)";
		IdaVolta = "Ida e Volta";
		SomenteIda = "Somente Ida";
		Pesquisar = "Pesquisar";
		AlterarStatusVoo = "Alterar Status de Voo";
		ControlarStatusVoo = "Controlar Status de Voo";
		AlterarStatus = "Alterar Status";
		Codigo = "Código";

		QuantidadeFileiras = "Quantidade de fileiras";
		QuantidadeAssentos = "Quantidade de assentos";

		AlterarAeronave = "Alterar Aeronave";
		Modelo = "Modelo";
		Consultar = "Consultar";
		Excluir = "Excluir";
		Cadastrar = "Cadastrar";
		Alterar = "Alterar";
		ExcluirAeronave = "Excluir Aeronave";
		TipoAeronave = "Tipo da Aeronave";
		ExcluirVoo = "Excluir Voo";
		ListaDeEscalas = "Lista de Escalas";
		RealizarCompra = "Realizar Compra";
		TransferirPassagem = "Transferir Passagem";
		SistemaAeroporto = "Sistema Aeroporto";
		Arquivo = "Arquivo";
		Sair = "Sair";
		Passagem = "Passagem";
		ComprarPassagem = "Comprar Passagem";
		CheckIn = "Check-In";
		RealizarCheckIn = "Realizar Check-In";
		Aeronave = "Aeronave";
		Voo = "Voo";
		Ajuda = "Ajuda";
		Suporte = "Suporte";
		PassagemAerea = "Passagem Aerea";
		Voos = "Voos";
		Finalizar = "Finalizar";
		Sobrenome = "Sobrenome";
		DataDeNascimento = "Data de nascimento";
		ListarAssentosDisponiveis = "Listar Assentos Disponíveis";
		PerfilPassageiro = "Perfil Passageiro";
		FormaDeTratamento = "Forma de tratamento";
		Adicionar = "Adicionar";
		TipoPagamento = "Tipo de Pagamento";
		Cartao = "Cartão";
		NomeTitularCartao = "Nome titular do cartão";
		Debito = "Débito";
		Credito = "Crédito";
		BandeiraCartao = "Bandeira Cartão";
		NumeroCartao = "Número Cartão";
		DataValidadeCartao = "Data validade cartão";
		NumeroSegurancaCartao = "Número de segurança do cartão";
		NumeroParcelas = "Número de parcelas";
		ValorParcela = "Valor da parcela";
		Dinheiro = "Dinheiro";
		ValorPago = "Valor pago";
		ValorTotal = "Valor total";
		ValorTroco = "Valor troco";
		Cheque = "Cheque";
		Conta = "Conta";
		FinalizarCompra = "Finalizar Compra";
		Celular = "Celular";
		ListarAssentos = "Listar assentos";
		TransferirAssentos = "Transferir assentos";
		TransferirPassagem = "Trasferir passagem";
		CodigoPassagem = "Código da passagem";
		BuscarVoo = "Buscar Voo";
		Sobre = "Sobre";
		ConsultarVooPassagem = "Consultar Voo - Pasagem";
		Genero = "Genero";
		Masculino = "Masculino";
		Feminino = "Feminino";
		Limpar = "Limpar";
		TipoPesquisa = "Tipo de Pesquisa";
		DadosVoo = "Dados do Voo";
		SomenteCodigo = "Somente pelo Código";
		Confirmado = "Confirmado";
		Encerrado = "Encerrado";
		Passageiro = "Passageiro";
		ExcluirPassageiro = "Excluir Passageiro";
		Senhora = "Senhora";
		Senhorita = "Senhorita";
		Senhor = "Senhor";
		QuantidadePassageiros = "Quantidade de Passageiros";
		AssentosDisponiveis = "Assentos Disponíveis";
		numeroCheque = "Número cheque";
		
	}
	
	public void toEnglish()
	{
		Masculino = "Male";
		Feminino = "Female";
		
		Sim = "Yes";
		Nao = "No";
		lang = "en";
		
		Dia = "Day";
		Mes = "Month";
		Ano = "Year";
		
		Ambos="Both";
		Cadastrar = "Register";
		CodigoPassageiro = "Passenger ID Number";
		Nome = "Name";
		Sobrenome = "Surname" ;
		Tipo = "Type";
		RG = "RG";
		CPF = "Security Number"; 
		Tratamento = "Treatment"; 
		DataNascimento = "Birth Date";
		Celular ="Cellphone Number";
		Email = "Email";
		
		AlterarPassageiro = "Alter Passenger";
		ConsultarPassageiro = "Query Passenger";
				
		CadastrarAeronave = "Register Aircraft";
		NomeAeronave = "Aircraft Name:";
		ModeloAeronave = "Aircracft Model:";
		QuantidadeColunas = "Seat Column Amount:";
		QuantidadeFileiras = "Seat Line Amount:";
		Limpar = "Erase";
		MenuPrincipal = "Main Menu";
		Sobre = "About";
		Passagem = "Ticket";
		Aeronave = "Aircraft";
		
		TipoPesquisa = "Type Search";
		DadosVoo = "Flight Data";
		SomenteCodigo = "Only the Code";
		Confirmado = "Confirmed";
		Encerrado = "Closed";
		Passageiro = "Passenger";
		
		Titulo = "Passage Air System";
		IncluirEscalas = "Include Scales";
		ExcluirEscalas = "Delete Scales";
		Salvar = "Save";
		AlterarVoo = "Change Flight";
		CodigoVoo = "Code Flight";
		Origem = "Origin";
		Escalas = "Scales";
		Destino = "Destination";
		Data = "Date";
		Hora = "Hour";
		NomeAeronave = "Name of Aircraft";
		Situacao = "Situation";
		EmEspera = "Waiting";
		Preco = "Price";
		Nome = "Name";
		QuantidadeAssentos = "Quantity seats";
		CadastrarAeronave = "Register Aircraft";
		QuantidadeFileiras = "Quantity ranks";
		AdicionarEscalas = "Add Scales";
		EscalasVoo = "Scales Flight";
		CadastrarVoo = "Register Flight";
		CancelarPassagem = "Cancel Passage";
		CodigoBilhete = "Ticket code";
		TempoRestante = "remaining time";
		ValorDevolvido = "Value to be returned";
		ContaBancaria = "Bank Account";
		Banco = "Bank";
		Agencia = "Agency";
		NumeroDaConta = "Account number";
		NomeTitular = "Name of holder";
		CPFTitular = "CPF holder";
		RealizarNovaPesquisa = "Perform new search";
		CodigoAeronave = "Code Aircraft";
		ConsultarAeronave = "Query Aircraft";
		Detalhes = "Details";
		Buscar = "Seek";
		RealizarNovaConsulta = "Undertake further consultation";
		ListarEscalasIda = "List scales Gone";
		Comprar = "Buy";
		ListarEscalasVolta = "List scales back";
		ConsultarVoo = "Query Flight";
		DataPartida = "Date of departure";
		HoraPartida = "Starting time";
		AeroportoDestino = "Destination airport";
		CidadeDestino = "Destination city";
		CustoIda = "Cost gone";
		CustoVolta = "Cost back";
		CustoTotal = "Total Cost";
		ListarEscalas = "List scales";
		Voltar = "Back";
		ConsultarVooIdaEVolta = "Consult Flight Roundtrip";
		Ida = "Going";
		Volta = "Return";
		DataIda = "Date from";
		DataVolta = "Return date";
		Passageiros1 = "Passengers (up to 1 year and 11 months)";
		Passageiros2 = "Passengers (up to 2 years and 11 months)";
		Passageiros3 = "Passengers (over 3 years)";
		IdaVolta = "Round trip";
		SomenteIda = "One-way";
		Pesquisar = "Search";
		AlterarStatusVoo = "Change Flight Status";
		ControlarStatusVoo = "Checking Flight Status";
		AlterarStatus = "Change Status";
		Codigo = "Code";

		QuantidadeFileiras = "Number of Rows";
		QuantidadeAssentos = "Number of seats";

		AlterarAeronave = "Change Aircraft";
		Modelo = "Model";
		Consultar = "Consult";
		Excluir = "Delete";
		Cadastrar = "Register";
		Alterar = "Change";
		ExcluirAeronave = "Delete Aircraft";
		TipoAeronave = "Type of Aircraft";
		ExcluirVoo = "Delete Flight";
		ListaDeEscalas = "List of Scales";
		RealizarCompra = "Perform Purchase";
		TransferirPassagem = "Download Pass";
		SistemaAeroporto = "Airport system";
		Arquivo = "File";
		Sair = "Exit";
		Passagem = "Passage";
		ComprarPassagem = "Buy Passage";
		CheckIn = "Check-In";
		RealizarCheckIn = "Perform Check-In";
		Aeronave = "Aircraft";
		Voo = "Flight";
		Ajuda = "Help";
		Suporte = "Bracket";
		PassagemAerea = "Passage Aerea";
		Voos = "Flight";
		Finalizar = "Finalize";
		Sobrenome = "Surname";
		DataDeNascimento = "Date of birth";
		ListarAssentosDisponiveis = "List Seats Available";
		PerfilPassageiro = "Passenger Profile";
		FormaDeTratamento = "Salutation";
		Adicionar = "ADD";
		TipoPagamento = "Payment Type";
		Cartao = "Card";
		NomeTitularCartao = "Name card holder";
		Debito = "Debt";
		Credito = "Credit";
		BandeiraCartao = "Flag Card";
		NumeroCartao = "Card number";
		DataValidadeCartao = "Validity Date Card";
		NumeroSegurancaCartao = "Number of card security";
		NumeroParcelas = "Number of plots";
		ValorParcela = "Value of the share";
		Dinheiro = "Money";
		ValorPago = "Amount paid";
		ValorTotal = "Value total";
		ValorTroco = "Value change";
		ExcluirPassageiro = "Delete Passenger";
		CadastrarPassageiro = "Register Passenger";
		Senhora = "Mrs.";
		Senhorita = "Miss";
		Senhor = "Mr.";
		QuantidadePassageiros = "Number of Passengers";
		AssentosDisponiveis = "Seats Available";
		numeroCheque = "Check number";
		
			
	}
	
	public  void toSpanish()
	{
		Sim = "Sí";
		Nao = "No";
		lang = "sp";
		
		Masculino = "Macho";
		Feminino = "Femenino";
		Genero = "Género";
		
		
		
		CadastrarAeronave = "Registro de Aeronaves";
		CadastrarPassageiro = "Registro de Pasajeros";
		NomeAeronave = "Nombre del avión";
		ModeloAeronave = "Aeromodelismo";
		QuantidadeColunas = "Número de columnas:";
		QuantidadeFileiras = "Número de filas:";
		Cadastrar = "Registro";
		Limpar = "Limpiar";
		TipoPesquisa = "Tipo de Búsqueda";
		DadosVoo = "Datos de Vuelo";
		SomenteCodigo = "Sólo el Código";
		Confirmado = "Confirmado";
		Encerrado = "Cerrado";
		Passageiro = "Pasajero";
		
		Titulo = "Sistema Pasaje Aerea";
		IncluirEscalas = "Incluya Scales";
		ExcluirEscalas = "Eliminar Scales";
		Salvar = "Guardar";
		AlterarVoo = "Cambiar vuelo";
		CodigoVoo = "Código Vuelo";
		Origem = "Origen";
		Escalas = "Scales";
		Destino = "Destino";
		Data = "Fecha";
		Hora = "Tiempo";
		NomeAeronave = "Nombre de aeronaves";
		Situacao = "Situación";
		EmEspera = "Espera";
		Preco = "Precio";
		Nome = "Nombre";
		QuantidadeAssentos = "Asientos Cantidad";
		CadastrarAeronave = "Registro Aeronaves";
		QuantidadeFileiras = "Cantidad filas";
		AdicionarEscalas = "Añadir Scales";
		EscalasVoo = "Scale Vuelo";
		CadastrarVoo = "Registrarse Vuelo";
		CancelarPassagem = "Cancelar Passage";
		CodigoBilhete = "Código Ticket";
		TempoRestante = "Tiempo restante";
		ValorDevolvido = "Valor a devolver";
		ContaBancaria = "Cuenta Bancaria";
		Banco = "Banco";
		Agencia = "Agencia";
		NumeroDaConta = "Número de cuenta";
		NomeTitular = "Nombre del titular";
		CPFTitular = "CPF";
		RealizarNovaPesquisa = "Realizar nueva búsqueda";
		CodigoAeronave = "Aviones Código";
		ConsultarAeronave = "Consulte Aviones";
		Detalhes = "Detalles";
		Buscar = "Buscar";
		RealizarNovaConsulta = "Llevar a cabo más consultas";
		ListarEscalasIda = "Escalas Lista Atrás";
		Comprar = "Comprar";
		ListarEscalasVolta = "Lista de las escalas de la espalda";
		ConsultarVoo = "Consulte Vuelo";
		DataPartida = "Fecha de salida";
		HoraPartida = "Hora de inicio";
		AeroportoDestino = "Aeropuerto de destino";
		CidadeDestino = "Cidade de destino";
		CustoIda = "Costo de va";
		CustoVolta = "Costo de Vuelta";
		CustoTotal = "Coste total";
		ListarEscalas = "escalas Lista";
		Voltar = "volver";
		ConsultarVooIdaEVolta = "Consulte Vuelo Ida y vuelta";
		Ida = "va";
		Volta = "volver";
		DataIda = "Fecha desde";
		DataVolta = "Fecha de regreso";
		Passageiros1 = "Pasajeros (hasta 1 año y 11 meses)";
		Passageiros2 = "Pasajeros (hasta 2 años y 11 meses)";
		Passageiros3 = "Los pasajeros (más de 3 años)";
		IdaVolta = "Ida y vuelta";
		SomenteIda = "Va";
		Pesquisar = "Investigación";
		AlterarStatusVoo = "Cambio del estado del vuelo";
		ControlarStatusVoo = "Comprobación del estado del vuelo";
		AlterarStatus = "Cambio de estado";
		Codigo = "Código";

		QuantidadeFileiras = "Número de filas";
		QuantidadeAssentos = "Número de asientos";

		AlterarAeronave = "Cambiar Aviones";
		Modelo = "Modelo";
		Consultar = "Consultar";
		Excluir = "borrar";
		Cadastrar = "registro";
		Alterar = "cambiar";
		ExcluirAeronave = "Eliminar Aviones";
		TipoAeronave = "Tipo da Aeronave";
		ExcluirVoo = "Eliminar Vuelo";
		ListaDeEscalas = "Lista de Scales";
		RealizarCompra = "Realizar Compra";
		TransferirPassagem = "Descarga Pass";
		SistemaAeroporto = "Sistema de Aeropuertos";
		Arquivo = "expediente";
		Sair = "Dejar";
		Passagem = "Pasaje";
		ComprarPassagem = "Comprar Passage";
		CheckIn = "Facturación";
		RealizarCheckIn = "Realizar Entradas";
		Aeronave = "Aeronave";
		Voo = "Vuelo";
		Ajuda = "Ayudar";
		Suporte = "Soporte";
		PassagemAerea = "Pasaje Aerea";
		Voos = "Vuelos";
		Finalizar = "Finalizar";
		Sobrenome = "apellido";
		DataDeNascimento = "Fecha de nacimiento";
		ListarAssentosDisponiveis = "Lista de asientos disponibles";
		PerfilPassageiro = "pasajeros Perfil";
		FormaDeTratamento = "Saludo";
		Adicionar = "añadir";
		TipoPagamento = "Tipo de pago";
		Cartao = "tarjeta";
		NomeTitularCartao = "Nombre del titular de la tarjeta";
		Debito = "Deuda";
		Credito = "Crédito";
		BandeiraCartao = "Tarjeta de la bandera";
		NumeroCartao = "Número de tarjeta";
		DataValidadeCartao = "Tarjeta de fecha de validez";
		NumeroSegurancaCartao = "Número de seguridad de la tarjeta";
		NumeroParcelas = "Número de parcelas";
		ValorParcela = "Valor de la cuota";
		Dinheiro = "Dinero";
		ValorPago = "Cantidad pagada";
		ValorTotal = "Valor total";
		ValorTroco = "Cambio de valores";
		Cheque = "Cheque";
		Conta = "Cuenta";
		FinalizarCompra = "Caja";
		Celular = "Celular";
		ListarAssentos = "Asientos de lista";
		TransferirAssentos = "Asientos de Transferencia";
		TransferirPassagem = "Paso Trasferir";
		CodigoPassagem = "Pase código";
		BuscarVoo = "Búsqueda de Vuelo";
		Sobre = "Sobre";
		ConsultarVooPassagem = "Pregunta vuelo - Recipiente de pesada";
		ExcluirPassageiro = "Eliminar Passajeros";
		Senhora = "Dama";
		Senhorita = "Sra.";
		Senhor = "Sr.";
		QuantidadePassageiros = "Número de pasajeros";
		AssentosDisponiveis = "Asientos Disponibles";
		numeroCheque = "Número de cheque";

	}
	
	
}
